### ISSUE TITLE
Missing packages from Stackage

### ISSUE THREAD

**Issue by RyanGlScott** [phadej/acme-kmett#1]
I noticed when cross-referencing this list with the [one from Stackage](https://github.com/fpco/stackage/blob/ec70f06b53c935740b73fa12ccb9a891dfbc1022/build-constraints.yaml#L540) that `acme-kmett` is missing several packages, including:

* `concurrent-supply`
* `exceptions`
* `fixed`
* `graphs`
* `half`
* `integration`
* `intern`
* `lca`
* `lens-properties`
* `monadic-arrays`
* `monad-products`
* `monad-st`
* `mtl`
* `semigroupoid-extras`
* `speculation`
* `unique`

**Comment by RyanGlScott** [comment]
Also, your list currently includes two deprecated packages, `hashable-extras` and `prelude-extras` (I'm not sure if this is intentional).

**Comment by RyanGlScott** [comment]
Also, thanks for curating this list—this helped me in the [other direction](https://github.com/fpco/stackage/pull/3272) as well :)

**Comment by phadej** [comment]
I had to add `free:exceptions` to `allow-newer` list. Is there plans for release of `exceptions-0.9`?

**Comment by RyanGlScott** [comment]
Good question. I'll look into that when I get a chance.
